"""occurrence overrides: move or skip a single event date

Revision ID: 626ff0dce2a6
Revises: c4e81d5a7f22
Create Date: 2026-09-04 14:14:29.622401
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '626ff0dce2a6'
down_revision = 'c4e81d5a7f22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_instances', sa.Column('original_starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_instances', sa.Column('override_note', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_event_instances_original_starts_at'), 'event_instances', ['original_starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_instances_original_starts_at'), table_name='event_instances')
    op.drop_column('event_instances', 'override_note')
    op.drop_column('event_instances', 'original_starts_at')
    # ### end Alembic commands ###
