"""record who created and last changed each announcement and event

Revision ID: 9cfba97c11c3
Revises: 626ff0dce2a6
Create Date: 2026-09-04 15:44:49.337947
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9cfba97c11c3'
down_revision = '626ff0dce2a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('created_by_name', sa.String(length=100), nullable=True))
    op.add_column('announcements', sa.Column('updated_by_name', sa.String(length=100), nullable=True))
    op.add_column('event_definitions', sa.Column('created_by_name', sa.String(length=100), nullable=True))
    op.add_column('event_definitions', sa.Column('updated_by_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    # Backfill from the audit log, which has recorded the actor since the
    # first release. Without this every existing row would show no author,
    # even though we know who made it.
    op.execute("""
        UPDATE announcements a SET created_by_name = sub.actor_name
        FROM (
            SELECT DISTINCT ON (entity_id) entity_id, actor_name
            FROM audit_log
            WHERE action = 'announcement.create' AND entity_id IS NOT NULL
            ORDER BY entity_id, at ASC
        ) sub
        WHERE a.id::text = sub.entity_id AND a.created_by_name IS NULL
    """)
    op.execute("""
        UPDATE event_definitions e SET created_by_name = sub.actor_name
        FROM (
            SELECT DISTINCT ON (entity_id) entity_id, actor_name
            FROM audit_log
            WHERE action = 'event.create' AND entity_id IS NOT NULL
            ORDER BY entity_id, at ASC
        ) sub
        WHERE e.id::text = sub.entity_id AND e.created_by_name IS NULL
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_definitions', 'updated_by_name')
    op.drop_column('event_definitions', 'created_by_name')
    op.drop_column('announcements', 'updated_by_name')
    op.drop_column('announcements', 'created_by_name')
    # ### end Alembic commands ###
