"""key bylines on discord id, not a frozen name

Revision ID: fe2f60025e83
Revises: 9cfba97c11c3
Create Date: 2026-09-04 16:00:45.238358
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fe2f60025e83'
down_revision = '9cfba97c11c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('created_by_id', sa.BigInteger(), nullable=True))
    op.add_column('announcements', sa.Column('updated_by_id', sa.BigInteger(), nullable=True))
    op.add_column('event_definitions', sa.Column('created_by_id', sa.BigInteger(), nullable=True))
    op.add_column('event_definitions', sa.Column('updated_by_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###

    # Backfill the ids from the audit log, which has recorded actor_discord_id
    # since the first release. Once these are set the display name is resolved
    # live, so a nickname change is reflected everywhere at once.
    for table, action in (("announcements", "announcement.create"),
                          ("event_definitions", "event.create")):
        op.execute(f"""
            UPDATE {table} t SET created_by_id = sub.actor_discord_id
            FROM (
                SELECT DISTINCT ON (entity_id) entity_id, actor_discord_id
                FROM audit_log
                WHERE action = '{action}' AND entity_id IS NOT NULL
                  AND actor_discord_id IS NOT NULL
                ORDER BY entity_id, at ASC
            ) sub
            WHERE t.id::text = sub.entity_id AND t.created_by_id IS NULL
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_definitions', 'updated_by_id')
    op.drop_column('event_definitions', 'created_by_id')
    op.drop_column('announcements', 'updated_by_id')
    op.drop_column('announcements', 'created_by_id')
    # ### end Alembic commands ###
